on:
  push:
    branches:
    - main

jobs:
  build:
    name: deploy to staging
    runs-on: ubuntu-22.04

    steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: cd docs
      run: cd ./docs

    - name: Install Dependencies
      run: npm install
    
    - name: build
      run: npm run build
