on:
  push:
    branches:
    - main

jobs:
  build:
    name: deploy to staging
    runs-on: ubuntu-22.04

    steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Copy resp
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: npm install
      working-directory: ./docs
    
    - name: build
      run: npm run build
      working-directory: ./docs

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload dist folder
        path: './docs/docs/.vitepress/dist'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      
